# Generated by Django 4.1.7 on 2023-03-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_answer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correct_questions', to='colors.answer')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colors.experiment')),
                ('incorrect_answer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incorrect_questions', to='colors.answer')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('r', 'Red'), ('b', 'Blue'), ('w', 'White')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colors.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colors.experiment')),
            ],
        ),
    ]
